<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/pure-min.css" integrity="sha384-X38yfunGUhNzHpBaEBsWLO+A0HDYOQi8ufWDkZ0k9e0eXz/tH3II7uKZ9msv++Ls" crossorigin="anonymous">
    <title><?php echo $title ?? 'Document'; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <main>
        <div class="pure-menu pure-menu-horizontal">
            <a href="/" class="pure-menu-heading pure-menu-link">Shooting Range</a>
            <ul class="pure-menu-list">
                <li class="pure-menu-item"><a href="/sessions" class="pure-menu-link">Sessions</a></li>
                <li class="pure-menu-item"><a href="/players" class="pure-menu-link">Players</a></li>
            </ul>
        </div>