<?php

// $players, $sessions, $highScore, $averageScore, $todaysSessions

$totalPlayers = count($players);
$totalSessions = count($sessions);

?>

<h2>Welcome to the Shooting Range Scoreboard</h2>
<div class="container">
    <div class="pure-g">
        <div class="pure-u-sm-1-1 pure-u-md-1-2 pure-u-lg-1-3">
            <div class="card">
                <h3>Total Players</h3>
                <div class="value"><?= htmlspecialchars($totalPlayers) ?></div>
            </div>
        </div>
        
        <div class="pure-u-sm-1-1 pure-u-md-1-2 pure-u-lg-1-3">
            <div class="card">
                <h3>Today's Sessions</h3>
                <div class="value"><?= htmlspecialchars(count($todaysSessions)) ?></div>
            </div>
        </div>
        
        <div class="pure-u-sm-1-1 pure-u-md-1-2 pure-u-lg-1-3">
            <div class="card">
                <h3>High Score</h3>
                <div class="value"><?= htmlspecialchars($highScore['totalScore']) ?><br/>By: <a href="/player/<?= htmlspecialchars($highScore['playerUUID']) ?>"><b><?= htmlspecialchars($highScore['playerName']) ?></b></a></div>
            </div>
        </div>
        
        <div class="pure-u-sm-1-1 pure-u-md-1-2 pure-u-lg-1-3">
            <div class="card">
                <h3>Average Score</h3>
                <div class="value"><?= htmlspecialchars($averageScore) ?></div>
            </div>
        </div>
        
        <div class="pure-u-sm-1-1 pure-u-md-1-2 pure-u-lg-1-3">
            <div class="card">
                <h3>Total Sessions</h3>
                <div class="value"><?= htmlspecialchars($totalSessions) ?></div>
            </div>
        </div>
    </div>
</div>